# This is a config for E2B sandbox template.
# You can use template ID (c0glsnm10ru0c1bogvjt) or template name (next-js-template) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("next-js-template") # Sync sandbox
# sandbox = await AsyncSandbox.create("next-js-template") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('next-js-template')

team_id = "924d399f-1792-4e57-b1eb-3758e729121b"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "next-js-template"
template_id = "c0glsnm10ru0c1bogvjt"
